
name: "TruffleHog"

on: [push, pull_request]

jobs:
  content-scan:
    name: Content Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      # scan for various types of keys and tokens
      - name: TruffleHog
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --entropy=False"
